name: codeveloper_tools
description: "Codeveloper Tools is a lightweight Flutter package that provides a suite of custom UI widgets and helper functions to accelerate your app development. Built for simplicity and consistency, our tools help you quickly integrate polished, responsive components into your projects."
version: 0.0.20
repository: https://github.com/KSABBAS/Codeveloper_Tools_Package
homepage: https://codevolper-portfolio.web.app

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  insta_image_viewer: ^1.0.4
  geolocator: ^13.0.2
  chewie: ^1.8.5
  video_player: ^2.9.2
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  path_provider: ^2.0.11
  mobile_scanner: ^6.0.3
  url_launcher: ^6.3.1
  pretty_qr_code: ^3.3.0
  just_audio: ^0.9.46
  record: ^5.2.0
  permission_handler: ^11.3.1
  flutter_sound_record_platform_interface: ^0.3.1
  flutter_sound: ^9.0.0
  intl: ^0.20.2

  plugin_platform_interface: ^2.1.8  # Updated from 'any' to specific version
  connectivity_plus: ^6.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codeveloper.tools  # Ensure this matches the package name in your Java/Kotlin file
        pluginClass: CodeveloperToolsPlugin  # Ensure this matches the main class name
      ios:
        pluginClass: CodeveloperToolsPlugin
      web:
        pluginClass: CodeveloperToolsWebPlugin
        fileName: codeveloper_tools_web.dart
      macos:
        pluginClass: CodeveloperToolsPlugin
      linux:
        pluginClass: CodeveloperToolsPlugin
      windows:
        pluginClass: CodeveloperToolsPluginCApi
        fileName: codeveloper_tools_plugin_c_api.cpp

  assets:
    - images/
