name: codeveloper_tools
description: "A suite of Flutter UI tools by Codeveloper, featuring custom widgets, media pickers , bars , and more to speed up app development."
version: 0.0.9
repository: https://github.com/KSABBAS/Codeveloper_Tools_Package
homepage: https://codeveloper.online

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  insta_image_viewer: ^1.0.4
  geolocator: ^13.0.2
  chewie: ^1.8.5
  video_player: ^2.9.2
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  path_provider: ^2.0.11
  mobile_scanner: ^6.0.3
  url_launcher: ^6.3.1
  pretty_qr_code: ^3.3.0
  just_audio: ^0.9.46
  record: ^5.2.0
  permission_handler: ^11.3.1
  flutter_sound_record_platform_interface: ^0.3.1
  flutter_sound: ^9.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Plugin section (dummy plugin for cross-platform support)
  plugin:
    platforms:
      android:
        package: codeveloper_tools
        pluginClass: CodeveloperToolsPlugin
      ios:
        pluginClass: CodeveloperToolsPlugin
      web:
        pluginClass: CodeveloperToolsPlugin
      macos:
        pluginClass: CodeveloperToolsPlugin
      windows:
        pluginClass: CodeveloperToolsPlugin
      linux:
        pluginClass: CodeveloperToolsPlugin

  # Uncomment and configure the assets/fonts sections if needed.
  assets:
    - images/
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
